language: objective-c
osx_image: xcode7.1
xcode_project: Stormpath.xcodeproj
xcode_scheme: Stormpath
xcode_sdk: iphonesimulator9.1
env:
 - XCTOOL_TEST_ENV_APIURL=http://sp-iostest-node.herokuapp.com
 - XCTOOL_TEST_ENV_APIURL=http://sp-iostest-laravel.herokuapp.com
before_install:
 - curl -s $XCTOOL_TEST_ENV_APIURL > /dev/null
 - brew update
 - brew outdated xctool || brew upgrade xctool